from commands2 import Command, Subsystem
from commands2.sysid import SysIdRoutine
import math
from phoenix6 import SignalLogger, swerve, units, utils
from typing import Callable, overload
from wpilib import DriverStation, RobotBase
from wpilib.sysid import SysIdRoutineLog
from wpimath.geometry import Pose2d, Rotation2d

from constants import SI, TunerSwerveDrivetrain, DriveConstants
import ntcore
from wpimath.kinematics import ChassisSpeeds
from utils.profiler import LoopTimer
from utils.swerve_facing_angle import FieldCentricFacingAngleAbsolute


class Drivetrain(Subsystem, TunerSwerveDrivetrain):
    """
    Class that extends the Phoenix 6 SwerveDrivetrain class and implements
    Subsystem so it can easily be used in command-based projects.

    Generated by the 2026 Tuner X Swerve Project Generator
    https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
    """

    _BLUE_ALLIANCE_PERSPECTIVE_ROTATION = Rotation2d.fromDegrees(0)
    """Blue alliance sees forward as 0 degrees (toward red alliance wall)"""
    _RED_ALLIANCE_PERSPECTIVE_ROTATION = Rotation2d.fromDegrees(180)
    """Red alliance sees forward as 180 degrees (toward blue alliance wall)"""

    @overload
    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        modules: list[swerve.SwerveModuleConstants],
        /,
    ) -> None:
        """
        Constructs a CTRE SwerveDrivetrain using the specified constants.

        This constructs the underlying hardware devices, so users should not construct
        the devices themselves. If they need the devices, they can access them through
        getters in the classes.

        :param drivetrain_constants: Drivetrain-wide constants for the swerve drive
        :type drivetrain_constants:  swerve.SwerveDrivetrainConstants
        :param modules:              Constants for each specific module
        :type modules:               list[swerve.SwerveModuleConstants]
        """
        ...

    @overload
    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        odometry_update_frequency: units.hertz,
        modules: list[swerve.SwerveModuleConstants],
        /,
    ) -> None:
        """
        Constructs a CTRE SwerveDrivetrain using the specified constants.

        This constructs the underlying hardware devices, so users should not construct
        the devices themselves. If they need the devices, they can access them through
        getters in the classes.

        :param drivetrain_constants:        Drivetrain-wide constants for the swerve drive
        :type drivetrain_constants:         swerve.SwerveDrivetrainConstants
        :param odometry_update_frequency:   The frequency to run the odometry loop. If
                                            unspecified or set to 0 Hz, this is 250 Hz on
                                            CAN FD, and 100 Hz on CAN 2.0.
        :type odometry_update_frequency:    units.hertz
        :param modules:                     Constants for each specific module
        :type modules:                      list[swerve.SwerveModuleConstants]
        """
        ...

    @overload
    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        odometry_update_frequency: units.hertz,
        odometry_standard_deviation: tuple[float, float, float],
        vision_standard_deviation: tuple[float, float, float],
        modules: list[swerve.SwerveModuleConstants],
        /,
    ) -> None:
        """
        Constructs a CTRE SwerveDrivetrain using the specified constants.

        This constructs the underlying hardware devices, so users should not construct
        the devices themselves. If they need the devices, they can access them through
        getters in the classes.

        :param drivetrain_constants:        Drivetrain-wide constants for the swerve drive
        :type drivetrain_constants:         swerve.SwerveDrivetrainConstants
        :param odometry_update_frequency:   The frequency to run the odometry loop. If
                                            unspecified or set to 0 Hz, this is 250 Hz on
                                            CAN FD, and 100 Hz on CAN 2.0.
        :type odometry_update_frequency:    units.hertz
        :param odometry_standard_deviation: The standard deviation for odometry calculation
                                            in the form [x, y, theta]ᵀ, with units in meters
                                            and radians
        :type odometry_standard_deviation:  tuple[float, float, float]
        :param vision_standard_deviation:   The standard deviation for vision calculation
                                            in the form [x, y, theta]ᵀ, with units in meters
                                            and radians
        :type vision_standard_deviation:    tuple[float, float, float]
        :param modules:                     Constants for each specific module
        :type modules:                      list[swerve.SwerveModuleConstants]
        """
        ...

    @overload
    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        arg0: None,
        arg1: None,
        arg2: None,
        arg3: None,
        /,
    ) -> None: ...

    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        arg0=None,
        arg1=None,
        arg2=None,
        arg3=None,
    ):
        Subsystem.__init__(self)
        TunerSwerveDrivetrain.__init__(
            self, drivetrain_constants, arg0, arg1, arg2, arg3
        )
        if not RobotBase.isReal():
            # Disable CAN warnings in sim
            for module in self.modules:
                module.drive_motor.sim_state  # just accessing it quiets stale warnings
        self.current_pose = Pose2d()
        self._brake_request = swerve.requests.SwerveDriveBrake()
        self.cached_state = self.get_state()

        self._zero_request = swerve.requests.ApplyRobotSpeeds().with_speeds(
            ChassisSpeeds(0, 0, 0)
        )
        self.movement = (
            swerve.requests.FieldCentric()
            .with_deadband(DriveConstants.MAX_TRANSLATIONAL_VELOCITY * 0.1)
            .with_rotational_deadband(
                DriveConstants.MAX_ANGULAR_VELOCITY * 0.2
            )  # Add a 10% deadband
            .with_drive_request_type(
                swerve.SwerveModule.DriveRequestType.OPEN_LOOP_VOLTAGE
            )  # Use open-loop control for drive motors
        )
        self.facing_angle = (
            FieldCentricFacingAngleAbsolute()
            .with_drive_request_type(
                swerve.SwerveModule.DriveRequestType.OPEN_LOOP_VOLTAGE
            )
            .with_max_abs_rotational_rate(DriveConstants.MAX_ANGULAR_VELOCITY)
        )

        self.heading_lock_movement = (
            swerve.requests.FieldCentricFacingAngle()
            .with_deadband(DriveConstants.MAX_TRANSLATIONAL_VELOCITY * 0.1)
            .with_rotational_deadband(DriveConstants.MAX_ANGULAR_VELOCITY * 0.1)
            .with_drive_request_type(
                swerve.SwerveModule.DriveRequestType.OPEN_LOOP_VOLTAGE
            )
        )

        # Tune the heading PID (adjust kP to taste)
        self.heading_lock_movement.heading_controller.setPID(10.0, 0.0, 0.00)
        self.heading_lock_movement.heading_controller.enableContinuousInput(
            -math.pi, math.pi
        )

        self.facing_angle.heading_controller.enableContinuousInput(-math.pi, math.pi)

        self.facing_angle.heading_controller.setPID(35.0 * 0.55, 0.0, 0.00)

        self.robot_centric_facing_angle = (
            swerve.requests.RobotCentricFacingAngle()
            .with_drive_request_type(
                swerve.SwerveModule.DriveRequestType.OPEN_LOOP_VOLTAGE
            )
            .with_max_abs_rotational_rate(DriveConstants.MAX_ANGULAR_VELOCITY)
            .with_forward_perspective(
                swerve.requests.ForwardPerspectiveValue.BLUE_ALLIANCE
            )
        )
        self.robot_centric_facing_angle.heading_controller.setPID(10.0, 0.0, 0.0)
        self.robot_centric_facing_angle.heading_controller.enableContinuousInput(
            -math.pi, math.pi
        )

        self._has_applied_operator_perspective = False
        """Keep track if we've ever applied the operator perspective before or not"""

        # Swerve requests to apply during SysId characterization
        self._translation_characterization = swerve.requests.SysIdSwerveTranslation()
        self._steer_characterization = swerve.requests.SysIdSwerveSteerGains()
        self._rotation_characterization = swerve.requests.SysIdSwerveRotation()
        self.nt = ntcore.NetworkTableInstance.getDefault()
        self.target_field_heading = Rotation2d(0)
        self.changeAng = False
        self.changeAngTelop = False
        self._sys_id_routine_translation = SysIdRoutine(
            SysIdRoutine.Config(
                # Use default ramp rate (1 V/s) and timeout (10 s)
                # Reduce dynamic voltage to 4 V to prevent brownout
                stepVoltage=4.0,
                # Log state with SignalLogger class
                recordState=lambda state: (
                    SignalLogger.write_string(
                        "SysIdTranslation_State",
                        SysIdRoutineLog.stateEnumToString(state),
                    )
                    and None
                ),
            ),
            SysIdRoutine.Mechanism(
                lambda output: self.set_control(
                    self._translation_characterization.with_volts(output)
                ),
                lambda log: None,
                self,
            ),
        )
        """SysId routine for characterizing translation. This is used to find PID gains for the drive motors."""

        self._sys_id_routine_steer = SysIdRoutine(
            SysIdRoutine.Config(
                # Use default ramp rate (1 V/s) and timeout (10 s)
                # Use dynamic voltage of 7 V
                stepVoltage=7.0,
                # Log state with SignalLogger class
                recordState=lambda state: (
                    SignalLogger.write_string(
                        "SysIdSteer_State", SysIdRoutineLog.stateEnumToString(state)
                    )
                    and None
                ),
            ),
            SysIdRoutine.Mechanism(
                lambda output: self.set_control(
                    self._steer_characterization.with_volts(output)
                ),
                lambda log: None,
                self,
            ),
        )
        """SysId routine for characterizing steer. This is used to find PID gains for the steer motors."""

        self._sys_id_routine_rotation = SysIdRoutine(
            SysIdRoutine.Config(
                # This is in radians per second², but SysId only supports "volts per second"
                rampRate=math.pi / 6,
                # Use dynamic voltage of 7 V
                stepVoltage=7.0,
                # Use default timeout (10 s)
                # Log state with SignalLogger class
                recordState=lambda state: (
                    SignalLogger.write_string(
                        "SysIdSteer_State", SysIdRoutineLog.stateEnumToString(state)
                    )
                    and None
                ),
            ),
            SysIdRoutine.Mechanism(
                lambda output: (
                    (
                        # output is actually radians per second, but SysId only supports "volts"
                        self.set_control(
                            self._rotation_characterization.with_rotational_rate(output)
                        ),
                        # also log the requested output for SysId
                        SignalLogger.write_double("Rotational_Rate", output),
                    )
                    and None
                ),
                lambda log: None,
                self,
            ),
        )
        """
        SysId routine for characterizing rotation.
        This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
        See the documentation of swerve.requests.SysIdSwerveRotation for info on importing the log to SysId.
        """

        self._sys_id_routine_to_apply = self._sys_id_routine_translation
        """The SysId routine to test"""

        self._loop_timer = LoopTimer("Drivetrain")

    def apply_request(
        self, request: Callable[[], swerve.requests.SwerveRequest]
    ) -> Command:
        """
        Returns a command that applies the specified control request to this swerve drivetrain.

        :param request: Lambda returning the request to apply
        :type request: Callable[[], swerve.requests.SwerveRequest]
        :returns: Command to run
        :rtype: Command
        """
        return self.run(lambda: self.set_control(request()))

    def sys_id_quasistatic(self, direction: SysIdRoutine.Direction) -> Command:
        """
        Runs the SysId Quasistatic test in the given direction for the routine
        specified by self.sys_id_routine_to_apply.

        :param direction: Direction of the SysId Quasistatic test
        :type direction: SysIdRoutine.Direction
        :returns: Command to run
        :rtype: Command
        """
        return self._sys_id_routine_to_apply.quasistatic(direction)

    def sys_id_dynamic(self, direction: SysIdRoutine.Direction) -> Command:
        """
        Runs the SysId Dynamic test in the given direction for the routine
        specified by self.sys_id_routine_to_apply.

        :param direction: Direction of the SysId Dynamic test
        :type direction: SysIdRoutine.Direction
        :returns: Command to run
        :rtype: Command
        """
        return self._sys_id_routine_to_apply.dynamic(direction)

    def periodic(self):
        self._loop_timer.start()
        self._refresh_state_cache()
        self.determine_turret_state()
        # Periodically try to apply the operator perspective.
        # If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
        # This allows us to correct the perspective in case the robot code restarts mid-match.
        # Otherwise, only check and apply the operator perspective if the DS is disabled.
        # This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
        if not self._has_applied_operator_perspective or DriverStation.isDisabled():
            alliance_color = DriverStation.getAlliance()
            if alliance_color is not None:
                self.set_operator_perspective_forward(
                    self._RED_ALLIANCE_PERSPECTIVE_ROTATION
                    if alliance_color == DriverStation.Alliance.kRed
                    else self._BLUE_ALLIANCE_PERSPECTIVE_ROTATION
                )
                self._has_applied_operator_perspective = True

        self._loop_timer.stop()

    def add_vision_measurement(
        self,
        vision_robot_pose: Pose2d,
        timestamp: units.second,
        vision_measurement_std_devs: tuple[float, float, float] | None = None,
    ):
        """
        Adds a vision measurement to the Kalman Filter. This will correct the
        odometry pose estimate while still accounting for measurement noise.

        Note that the vision measurement standard deviations passed into this method
        will continue to apply to future measurements until a subsequent call to
        set_vision_measurement_std_devs or this method.

        :param vision_robot_pose:           The pose of the robot as measured by the vision camera.
        :type vision_robot_pose:            Pose2d
        :param timestamp:                   The timestamp of the vision measurement in seconds.
        :type timestamp:                    second
        :param vision_measurement_std_devs: Standard deviations of the vision pose measurement
                                            in the form [x, y, theta]ᵀ, with units in meters
                                            and radians.
        :type vision_measurement_std_devs:  tuple[float, float, float] | None
        """
        TunerSwerveDrivetrain.add_vision_measurement(
            self,
            vision_robot_pose,
            utils.fpga_to_current_time(timestamp),
            vision_measurement_std_devs,
        )

    def get_pose_at_timestamp(self) -> Pose2d | None:
        """
        Return the pose at a given timestamp, if the buffer is not empty.

        :param timestamp: The timestamp of the pose in seconds.
        :type timestamp: second
        :returns: The pose at the given timestamp (or None if the buffer is empty).
        :rtype: Pose2d | None
        """
        timestamp = Drivetrain.get_timestamp()
        return TunerSwerveDrivetrain.sample_pose_at(
            self, utils.fpga_to_current_time(timestamp)
        )

    def _refresh_state_cache(self):
        self.cached_state = self.get_state()

    def get_pose(self) -> Pose2d:
        return self.cached_state.pose

    def get_speeds(self):
        return self.cached_state.speeds

    def get_rotation(self):
        return self.cached_state.pose.rotation()

    @staticmethod
    def get_timestamp():
        return utils.get_current_time_seconds()

    def drive_based_velocity(self, vx: float, vy: float, omega: float):
        """
        Drive the robot with the given velocities.

        :param vx: Velocity in the x direction (m/s).
        :param vy: Velocity in the y direction (m/s).
        :param omega: Angular velocity (rad/s).
        """
        self.set_control(
            self.movement.with_velocity_x(vx)
            .with_velocity_y(vy)
            .with_rotational_rate(omega)
        )

    def stop(self):
        self.set_control(swerve.requests.SwerveDriveBrake())

    def get_gyro_rotation(
        self,
    ):  # BW: Shouldn't really ever be used. Lowkey don't need this if our vision system is good.
        return self.pigeon2.getRotation2d()

    def reset_odometry_auto(self, pose: Pose2d):
        self.reset_pose(pose)

    def set_robot_centric_velocities(
        self, speeds: ChassisSpeeds
    ):  # BW needed for AutoBuilder since it only supports robot-centric control, but we want to use field-centric control for teleop
        if self.changeAng:
            self.set_control(
                self.robot_centric_facing_angle.with_velocity_x(speeds.vx)
                .with_velocity_y(speeds.vy)
                .with_target_direction(self.target_field_heading)
            )
        else:
            self.set_control(
                swerve.requests.RobotCentric()
                .with_velocity_x(speeds.vx)
                .with_velocity_y(speeds.vy)
                .with_rotational_rate(speeds.omega)
            )

    def determine_turret_state(self):
        drivePose = self.get_pose()
        if DriverStation.getAlliance() == DriverStation.Alliance.kRed:
            threshold_to_turret = drivePose.X() >= 11.15
        else:
            threshold_to_turret = drivePose.X() <= 5.3

        if threshold_to_turret:
            self.allow_center_auto_align = False
        else:
            self.allow_center_auto_align = True

    def point_at_pose(self, target_pose: Pose2d):
        current_pose = self.get_pose()
        if current_pose is not None:
            angle_to_target = math.atan2(
                target_pose.Y() - current_pose.Y(), target_pose.X() - current_pose.X()
            )
            print("Angle to target (degrees): ", math.degrees(angle_to_target))
            self.set_control(
                self.facing_angle.with_target_direction(Rotation2d(angle_to_target))
            )

    def reset_gyro(self):
        self.reset_rotation(
            Rotation2d(
                0
                if DriverStation.getAlliance() == DriverStation.Alliance.kBlue
                else 180 * SI.degrees_to_radians
            )
        )

    def hold_position_command(self):
        """Actively commands 0 velocity in X, Y, and yaw."""
        return self.apply_request(lambda: self._zero_request)

    def hold_position_and_aim_command(self):
        """Hold position; if changeAng is set, rotate toward target heading."""

        def _execute():
            if self.changeAng:
                self.set_control(
                    self.robot_centric_facing_angle.with_velocity_x(0)
                    .with_velocity_y(0)
                    .with_target_direction(self.target_field_heading)
                )
            else:
                self.set_control(self._zero_request)

        return self.run(_execute)

    def lock_wheels_command(self):
        """X-stance: physically locks wheels against pushing forces."""
        return self.apply_request(lambda: self._brake_request)
