from .auto_routine import AutoRoutine as AutoRoutine
from autos.leave import leave_auto as leave_auto
from autos.example_path import example_path_auto as example_path_auto
from autos.HP_Intake_Center_Pieces import HP_Intake_Center_Pieces_Auto as HP_Intake_Center_Pieces_Auto